---
title: "Ferramentas Gráficas"
author: "PET Estatística UFPR"
output:
  html_document:
    highlight: pygments
    toc: true
    theme: flatly
    keep_md: true
---

```{r, include=FALSE}
library(knitr)
opts_chunk$set(comment = NA)
```

## Ferramentas gráficas ##

No GIT, como vimos até agora, todo o gerenciamento do projeto é
realizado via *CLI (Command line interface)*, linhas de comando
interpretadas, geralmente pelo *bash*. Isso confere um maior controle e
segurança nas ações realizadas, mas em muitas situações os comandos e
*outpus* GIT não se apresentam de forma tão amigável seja pela difícil
memorização ou pela interatividade limitada.

Os comandos mais usuais como `git add`, `git commit` se tornam simples,
pois, mesmo para um usuário iniciante eles fazem parte do cotidiano em
um projeto sob versionamento GIT. Mas algumas situações que não ocorrem
com frequência, como por exemplo voltar a versão de um arquivo ou do
repositório, requerem comandos que são pouco utilizados e, não raramente
para realizá-las é necessário a consulta de algum material sobre
GIT. Outra situação onde a utilização dos comandos é dificultada, ocorre
para projetos maiores, onde muitos arquivos são alterados
simultaneamente e o procedimento de *commit* se torna trabalhoso, pois
é necessário listar todos os arquivos que fazem parte de um *commit*
no commando `git add`. Uma última situação exemplo em que o uso de *CLI*
não parece satisfatório é na comparação de arquivos, já usamos o comando
`git diff` na seção 3 e o *output* deste comando foi de simples
visualização, mas em arquivos maiores (com muitas linhas) a navegação
para verificar as alterações do arquivo não é tão amigável. Para
facilitar essas e outras situações surgem as *GUI's (Graphical User
Interfaces)*, interfaces gráficas para o usuário que incorporam comandos
GIT em *widgets*(botões, caixas de texto etc.) dispostos em um janela
gráfica de seu sistema operacional.

Neste capítulo apresentamos as principais *GUI's* para GIT em diferentes
plataformas sistemas UNIX, Mac OS X e Windows. Detalhes de download,
instalação e exemplos da utilização destas interfaces no fluxo de
trabalho de um projeto com versionamento **GIT** são descritos.

## Interfaces GIT ##

### git-gui (Nativo) ###

### gitk (Tcl/Tk) / gitg (Gtk) / gitx (MacOS) ###

### RabbitVCS (Linux/Unix) ###

### GitHub (MacOS e Windows) ###

### Outras Interfaces ###

Citar materiais de referência para instalação e utilização. 
Interfaces a serem comentadas:

* git-cola  
* Smart-Git  

Escolhidas por serem multiplataforma (Windows, Linux/Unix e MacOS)

Plugins e extensões, comentar a utilização do **GIT** em editores já
utilizados pela comunidade estatística. 

* Emacs (`magit`)
* RStudio
* Gedit

## Interfaces de comparação ##

Interfaces para auxílio na comparação de arquivos, não são exclusivas
para **GIT**, mas seu uso é intensificado em projetos versionados e/ou
colaborativos onde arquivos de diferentes versões precisam ser
comparados.

Para o **GIT** estas ferramentas de comparação são de utilidade na
visualização das alterações nas diferentes versões de um arquivo e
também quando se trabalha colaborativamente, onde no momento de mesclar
as contribuições de vários autores, pode ocorrer conflito e nessas horas
a possibilidade visualizar as linhas conflitantes lado a lado é de
grande valia.

### Meld ###

* Download e Instalação
* Utilização básica
* Utilização no **GIT** como `difftool` e/ou `mergetool`
* screenshots

### Outras interfaces ###

* kdiff3
* P4Merge

Citar materiais de referência para instalação e
utilização.

