---
title: "Projetos remotos"
author: "PET Estatística"
date: "29/10/2015"
output:
    html_document:
        highlight: pygments
        toc: true
        theme: flatly
        keep_md: true
---

##4. Projetos remotos##

###4.1 - Configuração de conexão ssh com servidor###
* Chaves públicas: introdução e breve descrição, facilidade da criação de um repositório devido a disponibilidade do servidor c3sl;
* Criando chave pública ssh: como gerar uma chave pública ssh que realizará uma conexão segura entre a máquina e o servidor;

###4.2 - Clone, push, pull, fetch###
* Introdução: colaborando em trabalhos coletivos;
* Clone: como copiar uma um repositório já existente para a sua máquina;
* Push: como transferir committs de um repositório local para um repositório remoto;
* Pull: como importar e mesclar arquivos do repositório remoto para a máquina;
* Fetch: como importar arquivos do repositório remoto para o repositório local, é possível verificar o arquivo antes de integrá-lo ao projeto com o git merge;
* Pull request: como facilitar a colaboração dos desenvolvedores.
